server:
  port: 8080
  context-path: /consul-client
spring:
  application:
    name: consul-client
  cloud:
    consul:
      host: 172.16.20.139
      port: 8500
      discovery:
        healthCheckPath: ${server.context-path}/health
        healthCheckInterval: 5s
